# This module and its contents were generated by Google's Gemini AI.
# I was too lazy to code this myself 😭

"""
Defines the Star class for creating and managing individual stars
used as a background effect in the game. Includes movement and drawing
with a simple glow effect.
"""

import pygame
import random


# Star class
class Star:
    """
    Represents a single star in the background, with properties for position,
    size, speed, color, and transparency. Handles movement and drawing
    with a glowing effect.
    """

    # Constants
    STAR_COLORS = [(200, 200, 255), (255, 255, 255), (180, 180, 255)]
    SCREEN_WIDTH, SCREEN_HEIGHT = 800, 800

    def __init__(self):
        """
        Initializes a new Star instance with random properties.
        Sets initial position, size, speed, color, and alpha.
        """
        self.x = random.randint(0, Star.SCREEN_WIDTH)
        self.y = random.randint(-Star.SCREEN_HEIGHT, Star.SCREEN_HEIGHT)
        self.radius = random.choice([1, 2])
        self.speed = random.uniform(1.5, 2.5) * self.radius  # Larger stars move slightly faster
        self.color = random.choice(Star.STAR_COLORS)
        self.alpha = random.randint(100, 255)


    def reset(self):
        """
        Resets the star's position and properties when it goes off-screen,
        making it appear at the top again with new characteristics.
        """
        self.x = random.randint(0, Star.SCREEN_WIDTH)
        self.y = random.randint(-Star.SCREEN_HEIGHT, 0)
        self.radius = random.choice([1, 2])
        self.speed = random.uniform(0.5, 1.5) * self.radius  # Larger stars move slightly faster
        self.color = random.choice(Star.STAR_COLORS)
        self.alpha = random.randint(100, 255)


    def move(self):
        """
        Updates the star's vertical position based on its speed.
        If the star moves off the bottom of the screen, it is reset.
        """
        self.y += self.speed
        if self.y > Star.SCREEN_HEIGHT:
            self.reset()
            self.y = random.randint(-50, -10)


    def draw(self, surface):
        """
        Draws the star and its glowing effect onto the given surface.

        :param surface: The Pygame surface to draw the star on.
        """
        # Draw glowing effect
        glow_radius = self.radius * 3
        for glow_alpha in range(30, 0, -10):
            glow_surface = pygame.Surface((glow_radius*2, glow_radius*2), pygame.SRCALPHA)
            glow_color = (*self.color, glow_alpha)
            pygame.draw.circle(glow_surface, glow_color, (glow_radius, glow_radius), glow_radius)
            surface.blit(glow_surface, (self.x - glow_radius, self.y - glow_radius))


        # Draw core star
        pygame.draw.circle(surface, self.color, (int(self.x), int(self.y)), self.radius)
